<?php

function wienimal_services_form_alter(array &$form)
{
    if (!isset($form['#title'])) {
        return;
    }

    $request = \Drupal::request();
    $service = \Drupal::service('wienimal_services.page_title');

    if (!$title = $service->getTitle($request)) {
        return;
    }

    $form['#title'] = $title;
}

function wienimal_services_locale_translation_projects_alter(&$projects)
{
    $path = \Drupal::getContainer()->get('extension.path.resolver')->getPath('module', 'wienimal_services') . '/translations/%language.po';
    $projects['wienimal_services']['info']['interface translation server pattern'] = $path;
}
